### PR TITLE
Feature/bl 788 track nearest bone

### PR DESCRIPTION
**Pull request by MattGrayUL**

### CODE REVIEW

**Review by NatGreenwood-UL — COMMENTED** [review]
Looks good overall, want to check with you in the morning about the change to AirPush using the fingertip because of the whole finger-curl issue. Would be nice to try this out solidly on kiosks before comitting to that change.

**Comment by MattGrayUL** [comment]
> Looks good overall, want to check with you in the morning about the change to AirPush using the fingertip because of the whole finger-curl issue. Would be nice to try this out solidly on kiosks before comitting to that change.

This was a mistake, I will change to the previously accepted tracking position

**Comment by MattGrayUL** [comment]
> Looks good overall, want to check with you in the morning about the change to AirPush using the fingertip because of the whole finger-curl issue. Would be nice to try this out solidly on kiosks before comitting to that change.

It uses the 'index stable' position which is the previously accepted position (near the proximal joint)

**Review by NatGreenwood-UL — APPROVED** [review]
Looked back over this, all looks good

**Pull request merged**
